#!/bin/bash -e

export LC_ALL=C
PN="gdb"

sudo=

[ -d sys-devel ] && cd sys-devel/${PN}
[ -d ../sys-devel ] && cd ../sys-devel/${PN}
if [ ! -e metadata.xml ] ; then
	echo "Run this in the ${PN} dir"
	exit 1
fi

export FEATURES="assume-digests -strict digest"
fetch() {
	${sudo} env GENTOO_MIRRORS=" " FEATURES="${FEATURES}" ebuild $1 fetch
}
manifest() {
	${sudo} ebuild $1 manifest
}

date

wget -nv --no-remove-listing -O /dev/null ftp://sources.redhat.com/pub/${PN}/snapshots/current/
l=".listing"
sed -i 's/\r$//' ${l}

# First unload ones that no longer exist.
ebuilds=$(echo ${PN}-?.?.50.*.ebuild)
for e in ${ebuilds} ; do
	f=$(echo "${e}" | sed -e 's:^gdb-:gdb-weekly-:g' -e 's:.ebuild:.tar.bz2:g')
	if grep -q "\<${f}$" ${l} ; then
		continue
	fi
	git rm -f ${e}
done

# Then load new ones.
snaps=$(grep -o ${PN}-weekly-'[[:digit:]]'.*.tar.* ${l} | \
	sed -e 's:.*-::' -e 's:.tar.*::')

src=$(ls ${PN}-*.ebuild | sort | tail -n 1)
for s in ${snaps} ; do
	dst="${PN}-${s}.ebuild"
	[[ ! -e ${dst} ]] || continue
	echo "### found ${s}"
	cp ${src} ${dst}
	fetch ${dst}
done

rm -f ${l}

if [[ -n ${src} ]] ; then
	manifest ${src}
fi
